CREATE TABLE farms (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  farm_name TEXT NOT NULL,
  address_1 TEXT,
  address_2 TEXT,
  city TEXT,
  zip_code INTEGER,
  phone_number TEXT,
  contact_name TEXT,
  farm_description TEXT,
  date_modified TIMESTAMPTZ NOT NULL DEFAULT now(),
  archived BOOLEAN default false
);