CREATE TYPE user_category AS ENUM (
  'Consumer',
  'Farmer'
);

CREATE TABLE users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_name TEXT NOT NULL unique,
  password TEXT NOT NULL,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  user_type user_category,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_modified TIMESTAMP
);

ALTER TABLE farms
  ADD COLUMN
    farm_owner_id INTEGER REFERENCES farms(id)
    ON DELETE SET NULL;